# Generated by Django 2.2.12 on 2020-05-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('inicial', 'Consulta Inicial'), ('evolucao', 'Consulta de Evolução')], default='inicial', max_length=55)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.IntegerField()),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuarioGeriatria.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Prescricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exameSolicitado', models.CharField(blank=True, max_length=255, null=True)),
                ('condutaTerapeutica', models.CharField(blank=True, max_length=255, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=255, null=True)),
                ('dieta', models.CharField(blank=True, max_length=255, null=True)),
                ('orientacao', models.CharField(blank=True, max_length=255, null=True)),
                ('encaminhamentos', models.CharField(blank=True, max_length=255, null=True)),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuarioGeriatria.Prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixaPrincipal', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaAtual', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaPregressa', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaFisiologica', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaFamiliar', models.CharField(blank=True, max_length=255, null=True)),
                ('exameFisico', models.CharField(blank=True, max_length=255, null=True)),
                ('avaliacaoFuncional', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaMedicamentosa', models.CharField(blank=True, max_length=255, null=True)),
                ('examesComplementares', models.CharField(blank=True, max_length=255, null=True)),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuarioGeriatria.Prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Hipoteses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hipotese', models.CharField(blank=True, max_length=255, null=True)),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prontuarioGeriatria.Prontuario')),
            ],
        ),
    ]
