# Generated by Django 2.2.12 on 2020-05-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescricoes',
            old_name='hipotese',
            new_name='condutaTerapeutica',
        ),
        migrations.AddField(
            model_name='prescricoes',
            name='dieta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescricoes',
            name='encaminhamentos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescricoes',
            name='exameSolicitado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescricoes',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
