# Generated by Django 3.2 on 2021-08-12 13:49

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacoes',
            name='testeNeuropsicologico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='sintomas',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'alergia': [], 'alguria': [], 'altApetite': [], 'altJatoUrinario': [], 'altPeso': [], 'altSono': [], 'ansiedade': [], 'artralgia': [], 'astenia': [], 'ativSexual': [], 'cefaleia': [], 'constipacao': [], 'convulsoes': [], 'corrimento': [], 'desmaio': [], 'diarreia': [], 'difAudicao': [], 'difCaminhar': [], 'difCheiro': [], 'difConcentracao': [], 'difEngolir': [], 'difFalar': [], 'difMastigar': [], 'difMemoria': [], 'difMovArticular': [], 'difPaladar': [], 'difVisao': [], 'disfagia': [], 'dispneia': [], 'disuria': [], 'dorAbdominal': [], 'dorColuna': [], 'dorMuscular': [], 'dorToracica': [], 'dormencia': [], 'edema': [], 'edemaArticular': [], 'extremidadesFrias': [], 'febre': [], 'fogacho': [], 'hematuria': [], 'hemorragiaDisgestiva': [], 'ideiaMorte': [], 'incontFecal': [], 'incontUrinaria': [], 'nausea': [], 'nicturia': [], 'palpitacoes': [], 'pirose': [], 'polidipsia': [], 'prisaoVentre': [], 'probDigestivo': [], 'probPele': [], 'pruidoVaginal': [], 'queda': [], 'resfriados': [], 'retUrinaria': [], 'roquidao': [], 'sangramento': [], 'sudorese': [], 'tonteiras': [], 'tosse': [], 'tremor': [], 'tristeza': [], 'urgMiccional': [], 'usoAlcool': [], 'usoFumo': [], 'vomito': [], 'zumbido': []}),
        ),
    ]
