# Generated by Django 3.2 on 2021-08-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testesneuropsicologicos',
            name='katz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testesneuropsicologicos',
            name='vft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testesneuropsicologicos',
            name='tcaVariabilidadeTempoReacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
