# Generated by Django 3.2 on 2021-07-27 19:15

import django.contrib.postgres.fields.hstore
from django.db import migrations
import prontuarioGeriatria.models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='data',
        ),
        migrations.AddField(
            model_name='sistema',
            name='sintomas',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=prontuarioGeriatria.models.jsonfield_default_value),
        ),
    ]
