# Generated by Django 3.2 on 2021-08-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testesneuropsicologicos',
            name='tcaIncorretas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testesneuropsicologicos',
            name='tcaOmitidas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testesneuropsicologicos',
            name='tcaTempoReacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testesneuropsicologicos',
            name='tcaVariabilidadeTempoReacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TesteComputadorizadoAtencaoVisual',
        ),
    ]
