# Generated by Django 3.2 on 2021-08-12 13:54

import django.contrib.postgres.fields.hstore
from django.db import migrations
import prontuarioGeriatria.models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0002_auto_20210812_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='sintomas',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=prontuarioGeriatria.models.jsonfield_default_value),
        ),
    ]
