# Generated by Django 2.2.12 on 2020-05-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0002_auto_20200506_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricoes',
            name='orientacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
