# Generated by Django 2.2.12 on 2020-05-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0003_prescricoes_orientacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(choices=[('inicial', 'Consulta Inicial'), ('evolucao', 'Consulta de Evolução')], default='inicial', max_length=55),
        ),
        migrations.AlterField(
            model_name='hipoteses',
            name='hipotese',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='avaliacaoFuncional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='exameFisico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='examesComplementares',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='historiaAtual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='historiaFamiliar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='historiaFisiologica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='historiaMedicamentosa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='historiaPregressa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='historiaSocial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacoes',
            name='queixaPrincipal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='condutaTerapeutica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='dieta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='encaminhamentos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='exameSolicitado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='orientacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
