# Generated by Django 2.2.12 on 2020-07-09 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0004_prontuario_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
