# Generated by Django 3.2 on 2021-09-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0004_auto_20210901_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacoes',
            name='testeNeuropsicologico',
        ),
    ]
