# Generated by Django 2.2.12 on 2021-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0005_auto_20200709_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='cefaleia',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='convulsoes',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='tonteiras',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
    ]
