# Generated by Django 2.2.12 on 2021-07-23 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0007_auto_20210720_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('informacao', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sistema',
            name='sistemaLista',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None),
        ),
    ]
