# Generated by Django 2.2.12 on 2021-07-23 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0008_auto_20210723_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemalista',
            name='sintoma',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None),
        ),
    ]
