# Generated by Django 2.2.12 on 2021-07-23 18:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0009_sistemalista_sintoma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='sistemaLista',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None), size=None),
        ),
    ]
