# Generated by Django 2.2.12 on 2021-07-23 19:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0010_auto_20210723_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='sistemaLista2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
