# Generated by Django 2.2.12 on 2021-07-23 19:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0011_sistema_sistemalista2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='sistemaLista2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
