# Generated by Django 2.2.12 on 2021-07-23 20:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import prontuarioGeriatria.models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0012_auto_20210723_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='sistemaLista2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=prontuarioGeriatria.models.jsonfield_default_value),
        ),
    ]
