# Generated by Django 2.2.12 on 2021-07-23 20:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import prontuarioGeriatria.models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarioGeriatria', '0014_auto_20210723_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='sintoma',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=prontuarioGeriatria.models.jsonfield_default_value, null=True),
        ),
    ]
