NACIONALIDADES_ESCOLHAS = [
    ('brasileiro', 'Brasileiro'),
    ('portuguesa', 'Portuguesa'),
    ('filipina', 'Filipina'),
    ('sulafricano', 'Sul-Africano'),
    ('zimbabweano', 'Zimbabweano'),
    ('namibiana', 'Namibiana'),
    ('boliviano', 'Boliviano'),
    ('chileno', 'Chileno'),
    ('colombiano', 'Colombiano'),
    ('costarriquenho', 'Costarriquenho'),
    ('cubano', 'Cubano'),
    ('dominicano', 'Dominicano'),
    ('equatoriano', 'Equatoriano'),
    ('salvadorenho', 'Salvadorenho'),
    ('granadino', 'Granadino'),
    ('guatemalteco', 'Guatemalteco'),
    ('guianês', 'Guianês'),
    ('guianense', 'Guianense'),
    ('haitiano', 'Haitiano'),
    ('hondurenho', 'Hondurenho'),
    ('jamaicano', 'Jamaicano'),
    ('mexicano', 'Mexicano'),
    ('nicaraguense', 'Nicaraguense'),
    ('panamenho', 'Panamenho'),
    ('paraguaio', 'Paraguaio'),
    ('peruano', 'Peruano'),
    ('portorriquenho', 'Portorriquenho'),
    ('dominicana', 'Dominicana'),
    ('saocristovense', 'São-cristovense'),
    ('saovicentino', 'São-vicentino'),
    ('santalucense', 'Santa-lucense'),
    ('surinames', 'Surinamês'),
    ('trindadense', 'Trindadense'),
    ('uruguaio', 'Uruguaio'),
    ('venezuelano', 'Venezuelano'),
    ('alema', 'Alemã'),
    ('austriaco', 'Austríaco'),
    ('belga', 'Belga'),
    ('croata', 'Croata'),
    ('dinamarques', 'Dinamarquês'),
    ('antiguano', 'Antiguano'),
    ('argentino', 'Argentino'),
    ('bahamense', 'Bahamense'),
    ('barbadense', 'Barbadense'),
    ('belizenho', 'Belizenho'),
    ('eslovaco', 'Eslovaco'),
    ('esloveno', 'Esloveno'),
    ('espanhol', 'Espanhol'),
    ('frances', 'Francês'),
    ('grego', 'Grego'),
    ('hungaro', 'Húngaro'),
    ('irlandes', 'Irlandês'),
    ('italiano', 'Italiano'),
    ('noruego', 'Noruego'),
    ('holandes', 'Holandês'),
    ('polones', 'Polonês'),
    ('ingles', 'Inglês'),
    ('gales', 'Galês'),
    ('escoces', 'Escocês'),
    ('romeno', 'Romeno'),
    ('russo', 'Russo'),
    ('servio', 'Sérvio'),
    ('sueco', 'Sueco'),
    ('suico', 'Suíço'),
    ('turco', 'Turco'),
    ('ucraniano', 'Ucraniano'),
    ('americano', 'Americano'),
    ('canadense', 'Canadense'),
    ('angolano', 'Angolano'),
    ('mocambicano', 'Moçambicano'),
    ('sulafricano', 'Sul-africano'),
    ('zimbabuense', 'Zimbabuense'),
    ('argelia', 'Argélia'),
    ('comorense', 'Comorense'),
    ('egipcio', 'Egípcio'),
    ('libio', 'Líbio'),
    ('marroquino', 'Marroquino'),
    ('ganes', 'Ganés'),
    ('queniano', 'Queniano'),
    ('ruandes', 'Ruandês'),
    ('ugandense', 'Ugandense'),
    ('bechuano', 'Bechuano'),
    ('marfinense', 'Marfinense'),
    ('camaronense', 'Camaronense'),
    ('nigeriano', 'Nigeriano'),
    ('somali', 'Somali'),
    ('australiano', 'Australiano'),
    ('neozelandes', 'Neozelandês'),
    ('afegao', 'Afegão'),
    ('saudita', 'Saudita'),
    ('armeno', 'Armeno'),
    ('bangladesh', 'Bangladesh'),
    ('chines', 'Chinês'),
    ('nortecoreano', 'Norte-coreano'),
    ('sulcoreano', 'Sul-coreano'),
    ('indiano', 'Indiano'),
    ('indonesio', 'Indonésio'),
    ('iraquiano', 'Iraquiano'),
    ('iraniano', 'Iraniano'),
    ('israelita', 'Israelita'),
    ('japones', 'Japonês'),
    ('malaio', 'Malaio'),
    ('nepales', 'Nepalês'),
    ('omanense', 'Omanense'),
    ('paquistanes', 'Paquistanês'),
    ('palestino', 'Palestino'),
    ('qatarense', 'Qatarense'),
    ('sirio', 'Sírio'),
    ('cingales', 'Cingalês'),
    ('tailandes', 'Tailandês'),
    ('timorense', 'Timorense'),
    ('arabe', 'Árabe'),
    ('vietnamita', 'Vietnamita'),
    ('iemenita', 'Iemenita')
]

ESTADOS_CIVIS_ESCOLHAS = [
    ('solteiro', 'Solteiro(a)'),
    ('casado', 'Casado(a)'),
    ('divorciado', 'Divorciado(a)'),
    ('viuvo', 'Viúvo(a)'),
    ('separadoJudicialmente', 'Separado(a) judicialmente')
]

GENEROS_ESCOLHAS = [
    (1, 'Feminino'),
    (2, 'Masculino')
]

ESCOLARIDADES_ESCOLHAS = [
    ('fundamental incompleto', 'Fundamental incompleto'),
    ('fundamental completo', 'Fundamental completo'),
    ('medio incompleto', 'Médio incompleto'),
    ('medio completo', 'Médio completo'),
    ('superior incompleto', 'Superior incompleto'),
    ('superior completo', 'Superior completo'),
    ('pos graduacao incompleto', 'Pós-Graduação incompleto'),
    ('pos graduacao completo', 'Pós-Graduação completo'),
    ('mestrado incompleto', 'Mestrado incompleto'),
    ('mestrado completo', 'Mestrado completo'),
    ('doutorado incompleto', 'Doutorado incompleto'),
    ('doutorado completo', 'Doutorado completo'),
]