# Generated by Django 2.2.12 on 2020-05-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='medic',
            new_name='medico',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=None, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='crm',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=55, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
