# Generated by Django 2.2.12 on 2020-05-27 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=55)),
                ('dataNascimento', models.DateField()),
                ('estadoCivil', models.CharField(blank=True, max_length=55, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=55, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=55, null=True)),
                ('crm', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
            bases=('autenticacao.user', models.Model),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('dataNascimento', models.DateField()),
                ('estadoCivil', models.CharField(blank=True, max_length=55, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=55, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=55, null=True)),
                ('cep', models.CharField(max_length=55)),
                ('endereco', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
                ('profissaoAtual', models.CharField(blank=True, max_length=55, null=True)),
                ('profissaoAnterior', models.CharField(blank=True, max_length=55, null=True)),
                ('renda', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('nome',),
                'abstract': False,
            },
        ),
    ]
