# Generated by Django 3.2 on 2021-07-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nome', models.CharField(max_length=55)),
                ('dataNascimento', models.DateField()),
                ('estadoCivil', models.CharField(blank=True, max_length=55, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=55, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=55, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=55)),
                ('endereco', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
                ('profissaoAtual', models.CharField(blank=True, max_length=55, null=True)),
                ('profissaoAnterior', models.CharField(blank=True, max_length=55, null=True)),
                ('renda', models.FloatField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('historiaPregressa', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaFisiologica', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaFamiliar', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.paciente')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
            },
        ),
    ]
