# Generated by Django 2.2.12 on 2020-06-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historiaPregressa', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaFisiologica', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('historiaFamiliar', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.Paciente')),
            ],
        ),
    ]
