# Generated by Django 3.2 on 2021-08-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
