# Generated by Django 3.2 on 2021-08-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='22', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(default='22', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='codigo',
            field=models.CharField(max_length=8),
        ),
    ]
