# Generated by Django 3.2 on 2021-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='codigo',
            field=models.CharField(max_length=8),
        ),
    ]
