# Generated by Django 2.2.12 on 2020-05-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ('nome',)},
        ),
    ]
