# Generated by Django 3.2 on 2022-01-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_auto_20220112_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
