# Generated by Django 3.2 on 2021-08-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_auto_20210817_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(max_length=255),
        ),
    ]
